"""
groq_client.py

Reusable Groq LLM client for the
US Tax & Legal RAG System.

Responsibilities
----------------
- Creates and manages the Groq client
- Sends prompts to the configured LLM
- Returns generated responses
- Logs latency and token usage
- Performs health checks

Author: Divyansh Kumar
Project: US Tax & Legal RAG System
"""

import logging
import time
from typing import Dict

from groq import Groq

from config import (
    GROQ_API_KEY,
    GROQ_MODEL,
)

# ---------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------
# Groq Client
# ---------------------------------------------------------------------

class GroqClient:
    """
    Reusable Groq client.

    The client is created once and reused for every
    prompt generation request.
    """

    def __init__(self):
        if not GROQ_API_KEY:
            raise ValueError(
                "GROQ_API_KEY not found in environment."
            )

        logger.info("=" * 65)
        logger.info("Initializing Groq Client")
        logger.info("Model : %s", GROQ_MODEL)

        try:
            self.client = Groq(
                api_key=GROQ_API_KEY
            )
            self.model = GROQ_MODEL
        except Exception as error:
            logger.exception(
                "Failed to initialize Groq client."
            )
            raise RuntimeError(
                "Could not initialize Groq client."
            ) from error

        logger.info("Groq client initialized successfully.")
        logger.info("=" * 65)

    # -----------------------------------------------------------------

    def health_check(self) -> bool:
        """
        Performs a lightweight API health check.

        Sends a tiny request to verify that:
        - API key is valid
        - model exists
        - network connection works

        Returns
        -------
        bool
            True if successful.
        """
        logger.info("=" * 65)
        logger.info("Running Groq Health Check")
        logger.info("=" * 65)

        logger.info("=" * 65)
        logger.info("Running Groq Health Check")
        logger.info("=" * 65)

        try:

            start_time = time.perf_counter()

            completion = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "user",
                        "content": "Hello"
                    }
                ],
                temperature=0.0,
                max_completion_tokens=5,
                timeout=30,
            )
            print("\n================ RAW COMPLETION ================\n")
            print(completion)
            print("\n===============================================\n")

            latency = time.perf_counter() - start_time

            logger.info("Groq Health Check Passed.")
            logger.info("Model : %s", self.model)
            logger.info("Latency : %.2f seconds", latency)

            # Optional: log the returned text for debugging
            try:
                reply = completion.choices[0].message.content
                logger.info("Model Reply : %s", repr(reply))
            except Exception:
                logger.info("Model reply could not be extracted.")

            logger.info("=" * 65)

            return True

        except Exception as error:

            logger.exception("Groq Health Check Failed.")

            logger.info("=" * 65)

            return False

    # -----------------------------------------------------------------

    def generate(
        self,
        prompt_text: str,
        temperature: float = 0.0,          # deterministic by default
        max_completion_tokens: int = 4096,
        timeout: int = 120,
    ) -> Dict:
        """
        Sends a prompt to Groq and returns the generated response.

        Parameters
        ----------
        prompt : str
            Complete prompt generated by PromptBuilder.

        temperature : float
            Sampling temperature (default 0.0 for reproducibility).

        max_completion_tokens : int
            Maximum response tokens.

        timeout : int
            Request timeout in seconds.

        Returns
        -------
        Dict
            {
                "answer": str,
                "model": str,
                "prompt_tokens": int,
                "completion_tokens": int,
                "total_tokens": int,
                "latency_seconds": float,
            }
        """
        if not prompt_text.strip():
            raise ValueError(
                "Prompt cannot be empty."
            )

        logger.info("=" * 65)
        logger.info("Generating LLM Response")
        logger.info("Model : %s", self.model)
        logger.info(
            "Prompt Characters : %d",
            len(prompt_text),
        )
        logger.info("=" * 65)

        start_time = time.perf_counter()

        try:
            completion = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "user",
                        "content": prompt_text,
                    }
                ],
                temperature=temperature,
                max_completion_tokens=max_completion_tokens,
                timeout=timeout,
            )

            # print("\n")
            # print("=" * 80)
            # print("RAW GROQ RESPONSE")
            # print("=" * 80)

            # print(completion)

            # print("=" * 80)
            print()

            logger.info(
                "Finish Reason : %s",
                completion.choices[0].finish_reason,
            )

            latency = (
                time.perf_counter() - start_time
            )

            answer = (
                completion
                .choices[0]
                .message
                .content
                .strip()
            )

            usage = getattr(
                completion,
                "usage",
                None,
            )

            prompt_tokens = (
                getattr(
                    usage,
                    "prompt_tokens",
                    0,
                )
                if usage
                else 0
            )

            completion_tokens = (
                getattr(
                    usage,
                    "completion_tokens",
                    0,
                )
                if usage
                else 0
            )

            total_tokens = (
                getattr(
                    usage,
                    "total_tokens",
                    0,
                )
                if usage
                else 0
            )

            logger.info(
                "Generation completed successfully."
            )
            logger.info(
                "Latency : %.2f seconds",
                latency,
            )
            logger.info(
                "Prompt Tokens : %d",
                prompt_tokens,
            )
            logger.info(
                "Completion Tokens : %d",
                completion_tokens,
            )
            logger.info(
                "Total Tokens : %d",
                total_tokens,
            )
            logger.info("=" * 65)

            return {
                "answer": answer,
                "model": self.model,
                "prompt_tokens": prompt_tokens,
                "completion_tokens": completion_tokens,
                "total_tokens": total_tokens,
                "latency_seconds": round(
                    latency,
                    2,
                ),
            }

        except Exception as error:
            logger.exception(
                "Groq generation failed."
            )
            raise RuntimeError(
                "Failed to generate response from Groq."
            ) from error


# ---------------------------------------------------------------------
# Interactive CLI
# ---------------------------------------------------------------------

def main():
    """
    Interactive command-line interface for testing the Groq client.

    This allows independent verification of:
    - API Key
    - Model
    - Network connectivity
    - Response generation

    before integrating with the RAG pipeline.
    """
    try:
        groq_client = GroqClient()

        if not groq_client.health_check():
            print("\nHealth check failed.\n")
            return

        print("\n")
        print("=" * 80)
        print("US TAX & LEGAL RAG SYSTEM")
        print("Groq Client")
        print("=" * 80)
        print("Type 'exit' or 'quit' to stop.\n")

        while True:
            prompt = input("Enter prompt: ").strip()

            if prompt.lower() in {"exit", "quit"}:
                print("\nExiting...\n")
                break

            if not prompt:
                print("Prompt cannot be empty.\n")
                continue

            try:
                response = groq_client.generate(
                    prompt_text=prompt
                )

                print("\n")
                print("=" * 80)
                print("MODEL")
                print("=" * 80)
                print(response["model"])

                print("\n")
                print("=" * 80)
                print("ANSWER")
                print("=" * 80)
                print(response["answer"])

                print("\n")
                print("=" * 80)
                print("STATISTICS")
                print("=" * 80)
                print(
                    f"Prompt Tokens     : {response['prompt_tokens']}"
                )
                print(
                    f"Completion Tokens : {response['completion_tokens']}"
                )
                print(
                    f"Total Tokens      : {response['total_tokens']}"
                )
                print(
                    f"Latency           : {response['latency_seconds']} sec"
                )
                print("=" * 80)
                print()

            except Exception as error:
                logger.exception(error)
                print(f"\nError: {error}\n")

    except Exception as error:
        logger.exception(error)
        print("\nFailed to initialize Groq Client.\n")


# ---------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------

if __name__ == "__main__":
    main()