"""
===========================================================
FastAPI Schemas

Purpose
-------
Defines request and response models for the FastAPI backend.

Author : Shyam Suman
Project : US Tax & Legal RAG System
===========================================================
"""

from typing import List

from pydantic import BaseModel, Field


# ==========================================================
# Request Schema
# ==========================================================

class QuestionRequest(BaseModel):
    """
    Request model for asking a legal question.
    """

    question: str = Field(
        ...,
        description="Natural language legal question.",
        examples=[
            "Can legal expenses be deducted under IRC Section 162?"
        ],
    )


# ==========================================================
# Reference Schema
# ==========================================================

class Reference(BaseModel):
    """
    Source reference returned by the RAG pipeline.
    """

    document_name: str = Field(
        ...,
        description="Name of the source document."
    )

    document_type: str = Field(
        ...,
        description="Type of legal document."
    )

    page_start: int = Field(
        ...,
        description="Starting page."
    )

    page_end: int = Field(
        ...,
        description="Ending page."
    )


# ==========================================================
# Response Schema
# ==========================================================

class AnswerResponse(BaseModel):
    """
    Response model returned by the API.
    """

    answer: str = Field(
        ...,
        description="Answer generated by the RAG pipeline."
    )

    latency: float = Field(
        ...,
        description="Time taken to generate the answer (seconds)."
    )

    model: str = Field(
        ...,
        description="LLM used to generate the answer."
    )

    references: List[Reference] = Field(
        default_factory=list,
        description="Source documents used to generate the answer."
    )